- name: Enable avahi-daemon service and reload it
  ansible.builtin.systemd:
    name: avahi-daemon
    enabled: true
    state: reloaded
- name: Restart network-manager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
