- name: Remove dvd-repository remains inside /etc/apt/sources.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: "^(deb cdrom:.+)"
    state: absent
- name: Removed broken VSCodium repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/vscodium.list
    state: absent

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
